# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addW.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from datetime import datetime

class Ui_addW(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

    def setupUi(self, addW):
        addW.setObjectName("addW")
        addW.resize(251, 251)
        self.verticalLayoutWidget = QtWidgets.QWidget(addW)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setAlignment(QtCore.Qt.AlignCenter)
        now = datetime.now()
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(now.year, now.month, now.day), QtCore.QTime(now.hour,now.minute,now.second)))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)

        self.retranslateUi(addW)
        self.save.clicked.connect(self.saveBM)
        QtCore.QMetaObject.connectSlotsByName(addW)

    def retranslateUi(self, addW):
        _translate = QtCore.QCoreApplication.translate
        addW.setWindowTitle(_translate("addW", "添加日程"))
        self.textEdit.setPlaceholderText(_translate("addW", "请输入日程："))
        self.save.setText(_translate("addW", "保存"))

    def saveBM(self):
        from mainUI import Ui_mainUI
        self.toDo_Text = self.textEdit.toPlainText()
        self.time_Text = self.dateTimeEdit.text()
        out = str(self.time_Text) +'\t' + str(self.toDo_Text)
        with open('Date.txt', 'a' , encoding = 'utf-8') as Date:
            if out[-1] == '\n':
                Date.write(out)
            else:
                Date.write(out + '\n')
            Date.close()
        self.close()
        self.SBM = Ui_mainUI()
        self.SBM.show()
